print('Welcome to school')
print('let"s introduced ourselves')
name = input ('what is your name? ')
print(name)
color = input ('what is your favorate color? ')
print(color)
food = input ('what is your favorate food? ')
print(food)
subject = input ('what is your favorate subject?' )
print (subject)
print(f"Everyone, meet {name}! {name}'s favorite color is {color}. {name}'s favorite food is {food}. {name}'s favorite subject is {subject}.")
